// ==========================================================
// DAY 20: INTEGRATING THE LIVE GOOGLE GEMINI AI BRAIN
// ==========================================================

require('dotenv').config();
const express = require('express');
// Import the official Google Gen AI SDK class
const { GoogleGenAI } = require('@google/genai');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());

// Initialize the Google Gen AI client instance using your hidden key from system memory
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

// GET Route: Basic Server Homepage
app.get('/', (req, res) => {
    res.send("<h1>AI Code Reviewer Server Engine: ONLINE</h1>");
});

// POST Route: Captures user code, shoots it to Gemini, and returns the analysis
app.post('/review', async (req, res) => {
    try {
        const userCode = req.body.code;

        if (!userCode) {
            return res.status(400).json({ error: "Please provide a valid code block inside the 'code' property." });
        }

        console.log("Sending code block to Gemini AI for structural review...");

        // Call the modern gemini-2.5-flash model via an asynchronous await block
        const aiResponse = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: `You are an expert software engineer code reviewer. Review this code block for bugs, logical flaws, and performance optimizations. Provide clear, concise bullet points for your review:\n\n${userCode}`,
        });

        // Extract the raw text result from the API response object
        const markdownReview = aiResponse.text;

        console.log("Review safely generated by Google AI! ✓");

        // Send the live analysis back to the caller as clean JSON
        res.json({
            success: true,
            review: markdownReview
        });

    } catch (error) {
        console.error("API Connection Error:", error);
        res.status(500).json({ error: "Failed to communicate with the Google AI engine." });
    }
});

app.listen(PORT, () => {
    console.log(`🚀 Day 20 AI Engine running live at http://localhost:${PORT}`);
});